export const notUsedphrases: Record<string, Record<string, string>> = {
    "weather": {
        "it is sunny": "c'è il sole",
        "the summer": "l'estate",
        "the seasons": "le stagioni",
        "the weather": "il tempo",
        "the autumn": "l'autumn",
        "fresh": "fresco",
        "the winter": "l'Inverno",
        "rain": "piovere",
        "snowing": "nevica",
        "the spring": "la primavera",
        "it's cloudy": "È Nuvoloso",
        "it's foggy": "C'è nebbia",
        "it's windy": "tira vento",
    },
    "clothes": {
        "clothes": "i vestiti",
        "designer clothes": "vestiti firmati",
        "earrings": "gli orecchini",
        "sweater": "maglia",
        "skirt": "gonna",
        "boots": "stivali",
        "pants": "pantaloni",
        "shoes": "scarpe",
        "button up shirt": "camicia",
        "tie": "cravatta",
        "jacket": "giacca", 
        "dress": "vestito",
        "rain coat": "impermeabile",
        "sweatshirt": "felpa",
        "jeans": "i jeans",
        "shorts": "pantaloni corti",
        "short sleeve shirt": "scarpe da ginnastica",
    },
    "school stuff": {
        "the theatre": "il teatrop",
        "school": "la scuola",
        "the apartments": "gli appartamenti",
        "the fountain": "la fontana",
        "the library": "la biblioteca",
        "the pool": "la piscina",
        "the tennic court": "il campo da tennis",
        "the sports field": "il campo sportivo",
        "stadium": "lo stadio",
        "book store": "la libreria",
        "cafeteria": "la mensa",
        "a backpack": "uno zaino",
        "a book": "un libro",
        "a calculator": "una calcolatrice",
        "a desk": "un banco",
        "a pen": "una penna",
        "piece of paper": "un foglio di carta",
        "a pencil": "una matita",
        "a desk (for a teacher)": "una cattedra",
        "an eraser (for chalkboard)": "un cancellino",
        "a chalk": "un gresso",
        "a chalkboard": "una lavagna",
        "a calendar": "un calendario",
        "a notebook": "un quaderno",
        "a map": "una carta geografica",
        "an eraser": "una gomma",
        "a newspaper": "un giornale",
        "a dictionary": "un dizionario",
        "an appointment book": "un agenda",
        "a clock": "un orologio",
        "a handbag": "una borsa",
        "a door": "una porta",
        "a screen": "uno schermo",
        "a trash bin": "un cestino",
        "building": "palazzo",
        "painting": "il quadro",
        "glass": "il bicchiere",
    },
}
export const phrases: Record<string, Record<string, string>> = {
    "past tense verbs": {
        "SUPERMAN-DAVE-C: S (verb)": "stare",
        "SUPERMAN-DAVE-C: S (past)": "stato",
        "SUPERMAN-DAVE-C: U (verb)": "uscire",
        "SUPERMAN-DAVE-C: U (past)": "uscito",
        "SUPERMAN-DAVE-C: P (verb)": "partire, piacere",
        "SUPERMAN-DAVE-C: P (past)": "partito, piaciuto",
        "SUPERMAN-DAVE-C: E(1) (verb)": "essere",
        "SUPERMAN-DAVE-C: E(1) (past)": "stato",
        "SUPERMAN-DAVE-C: R (verb)": "rimanere, ritornare, riuscire",
        "SUPERMAN-DAVE-C: R (past)": "rimasto, ritornato, riuscito",
        "SUPERMAN-DAVE-C: M (verb)": "morire",
        "SUPERMAN-DAVE-C: M (past)": "morto",
        "SUPERMAN-DAVE-C: A(1) (verb)": "andare",
        "SUPERMAN-DAVE-C: A(1) (past)": "andato",
        "SUPERMAN-DAVE-C: N (verb)": "nascere",
        "SUPERMAN-DAVE-C: N (past)": "nato",
        "SUPERMAN-DAVE-C: D (verb)": "diventare",
        "SUPERMAN-DAVE-C: D (past)": "diventato",
        "SUPERMAN-DAVE-C: A(2) (verb)": "arrivare",
        "SUPERMAN-DAVE-C: A(2) (past)": "arrivato",
        "SUPERMAN-DAVE-C: V (verb)": "venire",
        "SUPERMAN-DAVE-C: V (past)": "venuto",
        "SUPERMAN-DAVE-C: E(2) (verb)": "entrare",
        "SUPERMAN-DAVE-C: E(2) (past)": "entrato",
        "SUPERMAN-DAVE-C: C (verb)": "cadere",
        "SUPERMAN-DAVE-C: C (past)": "caduto",
    },
    "avere past tense": {
        "to open (past)": "ho aperto",
        "to drink (past)": "ho bevuto",
        "to ask (past)": "ho chiesto",
        "to close (past)": "ho chiupo",
        "to know (past)": "ho conosciuto",
        "to decide (past)": "ho diciso",
        "to say (past)": "ho detto",
        "to do (past)": "ho fatto",
        "to read (past)": "ho letto",
        "to put (past)": "ho messo",
        "to offer (past)": "ho offerto",
        "to lose (past)": "ho perso OR perduto",
        "to take (past)": "ho preso",
        "to answer (past)": "ho risposto",
        "to write (past)": "ho scripto",
        "to spend (past)": "ho speso",
        "to see (past)": "ho visto OR veduto"
    }
}